#pragma once

// Header file generated by Python script.

#ifndef _FREENGINE_H_
#define _FREENGINE_H_

#include <vector>
#include <string>
#include <array>
#include <cmath>
#include <algorithm>
#include <iostream>
#include <istream>
#include <sstream>
#include <fstream>
#include <map>
#include <set>
#include <functional>
#include <time.h>
#include <memory>

#include <GL/gl3w.h>
#include <GLFW/glfw3.h>

#include "..\src\Core\SafetyCheck.h"
#include "..\src\Core\Math.h"
#include "..\src\Core\Time.h"
#include "..\src\Event System\Action.h"
#include "..\src\Event System\Event.h"
#include "..\src\Rendering\Buffers\VertexBufferLayout.h"
#include "..\src\Rendering\Buffers\BaseBuffer.h"
#include "..\src\Rendering\Buffers\VertexBuffer.h"
#include "..\src\Rendering\Buffers\IndexBuffer.h"
#include "..\src\Rendering\VertexArray.h"
#include "..\src\Math\Vector2.h"
#include "..\src\Math\Vector3.h"
#include "..\src\Math\Vector4.h"
#include "..\src\Math\Quaternion.h"
#include "..\src\Math\Matrix4x4.h"
#include "..\src\Rendering\Shader.h"
#include "..\src\Rendering\Material.h"
#include "..\src\Rendering\Mesh.h"
#include "..\src\Rendering\Renderer.h"
#include "..\src\Core\Application.h"
#include "..\src\Core\Component.h"
#include "..\src\Core\Transform.h"
#include "..\src\Core\Camera.h"
#include "..\src\Core\Drawer.h"
#include "..\src\Core\SceneObject.h"
#include "..\src\Core\Scene.h"
#include "..\src\Core\PlayerLoop.h"


#endif //!_FREENGINE_H_
